version: "3.8"

services:
  web:
    build: .
    container_name: masoorian_web

  nginx:
    image: docker.io/nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web

