version: "3.8"

services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"

  nginx:
    image: docker.io/nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
