export const Consts = Object.freeze({
  title: "پرونده بیمار",
  firstName: "نام: ",
  lastName: "نام خانوادگی: ",
  insurance: "بیمه:",
  treatments: "درمان ها:",
  medicines: "دارو ها:",
  birthDate: "تاریخ تولد",
  ageInFirstSigns: "سن در اولین علائم بیماری:",
  age: "سال",
  gender: "جنسیت:",
  isPregnant: "آیا باردار است:",
  isBreastFeeding: "آیا در حال شیردهی است:",
  yes: "بله",
  no: "خیر",

  type: "پسوریازیس نوع",
  status: "وضعیت: ",
  formModalCompleted: "کامنت شما برای بیمار ثبت شد",
  psoriasis: "پسوریازیس",

  isVerified: "آیا تایید میکنید؟",
  doctorVerified: "دکتر پیشنهاد سامانه را تایید است",
  doctorDidnotVerified: "دکتر پیشنهاد سامانه را تایید نکرده است",
  doctorName: "اسم دکتر: ",

  diagnosisForm: "احتمال ابتلا",
  diagnosisType: "نوع بیماری بر اساس فرم",
  diagnosisImage: "نوع بیماری بر اساس عکس",
  selectDiagnosisType: "انتخاب نوع بیماری",
  diagnosisTypeByDoctor: "نوع بیماری تشخیص داده شده توسط دکتر: ",

  addComment: "اضافه کردن کامنت",
  comments: "کامنت های دکتر",
  noComments: "کامنتی وجود ندارد",
  enterCommentHere: "کامنت خود را اینجا وارد کنید",
  commentModal: "کامنت های مربوطه",
  comment: "نظر دکتر: ",

  formNumber: "فرم شماره ی ",
  seeFormInfo: "مشاهده ی فرم",
});
