export const Consts = Object.freeze({
  title: "پرونده بیمار",
  firstName: "نام: ",
  lastName: "نام خانوادگی: ",
  insurance: "بیمه:",
  treatments: "درمان ها:",
  medicines: "دارو ها:",
  birthDate: "تاریخ تولد",
  ageInFirstSigns: "سن در اولین علائم بیماری:",
  age: "سال",
  gender: "جنسیت:",
  isPregnant: "آیا باردار است:",
  isBreastFeeding: "آیا در حال شیردهی است:",
  yes: "بله",
  no: "خیر",
  diagnosisForm: "احتمال ابتلا",
  diagnosisType: "نوع بیماری بر اساس فرم",
  diagnosisImage: "نوع بیماری بر اساس عکس",
  click: "کلیک کنید",
  isVerifeid: "آیا تایید میکنید؟",
  selectDiagnosisType: "انتخاب نوع بیماری",
  addComment: "اضافه کردن کامنت",
  comments: "کامنت های دکتر",
  noComments: "کامنتی وجود ندارد",
  enterCommentHere: "کامنت خود را اینجا وارد کنید",
  commentModal: "کامنت های مربوطه",

  status: "وضعیت: ",
  formModalCompleted: "کامنت شما برای بیمار ثبت شد",
  psoriasis: "پسوریازیس",
});
