export const Consts = Object.freeze({
  congrats: "تبریک می گوییم!",
  fileCreated: "پرونده الکترونیک سلامت شما ایجاد شد",
  canContinue:
    "می‌توانید با ثبت درخواست‌های مختلف به دریافت توصیه بیماری خود برسید.",
  selfCare: "آموزش خود مراقبتی",
  dieseaseType: "انواع بیماری و درمان ها",
  createFile: "تشکیل پرونده",
  click: "کلیک کنید",
  noFile: "پرونده ای تشکیل نشده!",
  goMakeFile: "با رفتن به بخش تشکیل پرونده، پرونده الکترونیکی خود را بسازید",
  profileUpdate: "آپدیت پروفایل",
  diagnosisByForm: "تشخیص نوع بیماری",
  diagnosisByImage: "تشخیص از روی عکس",
  diagnosisByQuestionnaire: "تشخیص بیماری",
  notificationTitle: "اعلانات اخیر",
  date: "تاریخ:",
  hours: "ساعت",
  seeDoctorComment: "مشاهده کامنت دکتر",
  doctorComments: "کامنت های دکتر",
  doctorVerified: "دکتر پیشنهاد سامانه را تایید است",
  doctorDidnotVerified: "دکتر پیشنهاد سامانه را تایید نکرده است",
  type: "پسوریازیس نوع",
  comment: "نظر دکتر: ",
  diagnosisTypeByDoctor: "نوع بیماری تشخیص داده شده توسط دکتر: ",
});
