import { GenderEnum } from "@/utils/enum/gender-enum";

export const Consts = Object.freeze({
  title: "اطلاعات بیمار را وارد کنید",
  subTitle: "تکمیل پرونده الکترونیکی سلامت",
  continue: "ادامه",
  confirmAndContinue: "تایید و ادامه",
  edit: "ویرایش",
  fillFormIncomplete: "لطفا فرم را کامل کنید",
  fillFormError: "مشکلی در ارسال فرم بوجود آمده، لطفا مجددا تلاش کنید",
  formModalCompleted: "پرونده الکترونیک سلامت برای بیمار ایجاد شد.",
});

export const FormItems = [
  {
    label: "نام",
    placeholder: "نام بیمار را وارد کنید",
    type: "text",
    width: "1/4",
    key: "first_name",
  },
  {
    label: "نام خانوادگی",
    placeholder: "نام خانوادگی بیمار را وارد کنید",
    type: "text",
    width: "1/4",
    key: "last_name",
  },
  {
    label: "تاریخ تولد",
    placeholder: "تاریخ تولد بیمار را وارد کنید",
    type: "date",
    width: "1/2",
    key: "birth_date",
  },
  {
    label: "شغل",
    placeholder: "شغل بیمار را وارد کنید",
    type: "text",
    width: "1/2",
    key: "job",
  },
  {
    label: "کد ملی",
    placeholder: "کد ملی بیمار را وارد کنید",
    type: "text",
    width: "1/2",
    key: "national_id",
  },
  {
    label: "جنسیت",
    type: "radio",
    options: [
      { label: "مرد", value: "Male" },
      { label: "زن", value: "Female" },
    ],
    width: "1/4",
    key: "gender",
  },
  {
    label: "باردار هستید؟",
    type: "radio",
    options: [
      { label: "بله", value: true },
      { label: "خیر", value: false },
    ],
    width: "1/4",
    key: "is_pregnant",
    condition: (formValues) => formValues.gender === GenderEnum.FEMALE,
  },
  {
    label: "در حال شیردهی هستید؟",
    type: "radio",
    options: [
      { label: "بله", value: true },
      { label: "خیر", value: false },
    ],
    width: "1/4",
    key: "is_breastfeeding",
    condition: (formValues) => formValues.gender === GenderEnum.FEMALE,
  },
  {
    label: "وضعیت تاهل",
    type: "radio",
    options: [
      { label: "متاهل", value: true },
      { label: "مجرد", value: false },
    ],
    width: "1/4",
    key: "is_married",
  },
  {
    label: "تعداد فرزندان",
    placeholder: "تعداد فرزندان بیمار را وارد کنید",
    type: "number",
    width: "1/2",
    key: "number_of_children",
    condition: (formValues) => formValues.is_married,
  },

  // New Items
  {
    label: "تحصیلات",
    placeholder: "تحصیلات بیمار را وارد کنید",
    type: "text",
    width: "1/2",
    key: "education",
  },
  {
    label: "درآمد ماهانه (به تومان)",
    placeholder: "درآمد ماهانه بیمار را وارد کنید",
    type: "number",
    width: "1/2",
    key: "avg_salary",
  },

  {
    label: "سن در اولین علائم",
    placeholder: "سن در اولین علائم را وارد کنید",
    type: "number",
    width: "1/2",
    key: "age_in_first_sings",
  },

  {
    label: "آخرین مراجعه به پزشک",
    placeholder: "تاریخ آخرین مراجعه به پزشک",
    type: "date",
    width: "1/2",
    key: "last_doctor_visit",
  },
  {
    label: "زمان تشخیص بیماری",
    placeholder: "زمان تشخیص بیماری را وارد کنید",
    type: "date",
    width: "1/2",
    key: "detection_time",
  },
  {
    label: "نوع بیمه",
    placeholder: "نوع بیمه بیمار را وارد کنید",
    type: "text",
    width: "1/2",
    key: "insurance",
  },
  {
    label: "شماره تلفن",
    placeholder: "شماره تلفن بیمار را وارد کنید",
    type: "text",
    width: "1/2",
    key: "phone_number",
  },
  {
    label: "داروها",
    type: "select",
    multiSelect: true,
    options: [
      "Vitamin D analogues",
      "Corticosteroids",
      "Dianthrol",
      "Retinoids",
      "Tacrolimus",
      "Keratolytic agents",
      "Acitretin",
      "Methotrexate",
      "Cyclosporine",
      "Apremilast",
      "Fumaric Acid Esters",
      "Mycophenolate Mofetil",
      "Etanercept",
      "Adalimumab",
      "Infliximab",
      "Certolizumabpegol",
      "Ustekinumab",
      "Secukinumab",
      "Ixekizumab",
      "Brodalumab",
      "Guselkumab",
      "Calcipotriene",
      "Tazarotene",
      "Acitretin",
      "Adalimumab",
      "Etanercept",
      "Infliximab",
      "Ustekinumab",
      "Secukinumab",
      "Ixekizumab",
      "Methotrexate",
      "Cyclosporine",
      "Betamethasone",
      "Dipropionate",
      "Clobetasol",
      "Propionate",
      "Betamethasone Dipropionate and salicylic acid",
      "Abatacept",
      "Brodalumab",
      "Certolizumab pegol",
      "Guselkumab",
    ],
    width: "full",
    key: "medicines",
  },
  {
    label: "درمان‌ها",
    type: "checkbox",
    type: "select",
    multiSelect: true,
    options: [
      "درمان موضعی",
      "درمان خوراکی",
      "درمان بیولوژیکی و درمان تزریقی",
      "فتوتراپی",
    ],
    width: "full",
    key: "treatments",
  },
  {
    label: "شهر محل سکونت",
    placeholder: "شهر محل سکونت بیمار را وارد کنید",
    type: "text",
    width: "full",
    key: "city",
  },
  {
    label: "آدرس دقیق",
    placeholder: "آدرس دقیق بیمار را وارد کنید",
    type: "text",
    width: "full",
    key: "address",
  },
];
