name: Deploy masoorian project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # - name: Install Docker
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
      #     sudo apt-get install -y \
      #       ca-certificates \
      #       curl \
      #       gnupg \
      #       lsb-release  
      #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      #     echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
      #     sudo apt-get update
      #     sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      # - name: Install Docker Compose
      #   run: |
      #     sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      #     sudo chmod +x /usr/local/bin/docker-compose

      # - name: Configure Docker daemon
      #   run: |
      #     echo '{ "registry-mirrors": ["https://registry-1.docker.io/"] }' | sudo tee /etc/docker/daemon.json
      #     sudo systemctl restart docker

      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Build Docker image
      #   run: docker-compose -f docker-compose.yml build

      # - name: List Docker images
      #   run: docker images

      # - name: Tag Docker image
      #   run: docker tag masoorian-medical-web:latest docker.io/iminiume/masoorian-web-image:latest

      # - name: Push image to Docker hub
      #   run: docker push docker.io/iminiume/masoorian-web-image:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Setup SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@138.68.177.169 -p 7450 << 'EOF'
          cd ~/masoorian_mdical/masoorian-medical
          git pull origin main
          docker-compose up --build -d
          EOF
