name: Deploy Next.js with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Build Docker image
      #   run: docker-compose -f docker-compose.yml build

      # - name: Tag Docker image
      #   run: docker tag masoorian-web-image:latest iminiume/masoorian-web-image:latest

      # - name: Push image to Docker hub
      #   run: docker push iminiume/masoorian-web-image:latest

          # sudo docker pull iminiume/masoorian-web-image:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Setup SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@5.34.199.51 << 'EOF'
            cd ~/masoorian_web/masoorian-medical
            git pull origin main 
            docker-compose -f docker-compose.yml up -d build
          EOF
