name: Deploy Next.js with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build project
        run: npm run build

      # Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: docker build -t iminiume/masoorian-web-image:latest .

      # Push Docker image to DockerHub
      - name: Push Docker image
        run: docker push iminiume/masoorian-web-image:latest

      # Setup SSH agent and add private key
      - name: Setup SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Optional: Deploy to a server (replace with your actual deployment steps)
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@5.34.199.51 << 'EOF'
          sudo docker pull iminiume/masoorian-web-image:latest
          sudo docker stop masoorian-web || true
          sudo docker rm masoorian-web || true
          sudo docker run -d -p 3000:3000 --name masoorian-web iminiume/masoorian-web-image:latest
          EOF
