name: Deploy masoorian project

on:
  push:
    branches:
      - main

concurrency:
  group: masoorian-main
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # - name: Build Docker image
      #   run: |
      #     echo "$DOCKER_PASSWORD" | docker login registry.hamdocker.ir/mahdimahdavimaz -u "$DOCKER_USERNAME" --password-stdin && \
      #     docker build -t registry.hamdocker.ir/mahdimahdavimaz/masoorian-web-image . && \
      #     docker push registry.hamdocker.ir/mahdimahdavimaz/masoorian-web-image
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Setup SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        env:
          DOCKER_USERNAME: mahdimahdavimaz
          DOCKER_PASSWORD: fz4rhsAbFOgjOcQuA1!
        run: |
          ssh -o StrictHostKeyChecking=no root@139.59.166.85 << 'EOF'

            set -x

            export DOCKER_USERNAME="$DOCKER_USERNAME"
            export DOCKER_PASSWORD="$DOCKER_PASSWORD"

            if [[ -z "${DOCKER_USERNAME}" ]]; then
              echo "DOCKER_USERNAME is not set. Please check your GitHub Secrets."
              exit 1
            fi

            function docker_login() {
              echo "Logging into Docker registry..."
              echo "$DOCKER_PASSWORD" | sudo docker login registry.hamdocker.ir/mahdimahdavimaz -u "$DOCKER_USERNAME" --password-stdin
            }

            function pull_docker_image() {
              echo "Pulling the latest Docker image..."
              sudo docker pull registry.hamdocker.ir/mahdimahdavimaz/masoorian-web-image
            }

            function stop_old_container() {
              echo "Stopping any existing container..."
              sudo docker stop masoorian-web || true
            }

            function remove_old_container() {
              echo "Removing old container..."
              sudo docker rm masoorian-web || true
            }

            function run_new_container() {
              echo "Starting the new container..."
              sudo docker run -d --name masoorian-web -p 3001:3001 registry.hamdocker.ir/mahdimahdavimaz/masoorian-web-image
            }

            # Execute the functions in order
            docker_login
            pull_docker_image
            stop_old_container
            remove_old_container
            run_new_container

          EOF
