name: Deploy masoorian project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          # docker-compose up --build -d
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Setup SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@138.68.177.169 -p 7450 << 'EOF'
          cd ~/masoorian_mdical/masoorian-medical
          git pull origin main
          docker-compose up -d --build
          EOF
